apiVersion: v1
kind: Service
metadata:
  name: efkpoc
  namespace: default
  labels:
    app: efkpoc
spec:
  type: LoadBalancer
  selector:
    app: efkpoc
  ports:
    - name: http
      port: 80
      targetPort: 8081
