apiVersion: apps/v1
kind: Deployment
metadata:
  name: efkpoc
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: efkpoc
      version: 'v1'
  template:
    metadata:
      labels:
        app: efkpoc
        version: 'v1'
    spec:
      containers:
        - name: efkpoc-app
          image: ghcr.io/imkunyoung/efk-poc/efkpoc
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: JHIPSTER_SECURITY_AUTHENTICATION_JWT_BASE64_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: secret
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mariadb://efkpoc-mariadb.default.svc.cluster.local:3306/efkpoc?useLegacyDatetimeCode=false&serverTimezone=UTC
            - name: SPRING_LIQUIBASE_URL
              value: jdbc:mariadb://efkpoc-mariadb.default.svc.cluster.local:3306/efkpoc?useLegacyDatetimeCode=false&serverTimezone=UTC
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: efkpoc-mariadb
                  key: mariadb-root-password
            - name: SPRING_SLEUTH_PROPAGATION_KEYS
              value: 'x-request-id,x-ot-span-context'
            - name: JAVA_OPTS
              value: ' -Xmx256m -Xms256m'
            - name: SERVER_SHUTDOWN
              value: graceful
          resources:
            requests:
              memory: '512Mi'
              cpu: '500m'
            limits:
              memory: '1Gi'
              cpu: '1'
          ports:
            - name: http
              containerPort: 8081
          readinessProbe:
            httpGet:
              path: /management/health/readiness
              port: http
            initialDelaySeconds: 20
            periodSeconds: 15
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /management/health/liveness
              port: http
            initialDelaySeconds: 120
