apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: elastic
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: elastic/elasticsearch:7.17.10
        env:
        - name: discovery.type
          value: single-node
        - name: ELASTICSEARCH_USERNAME
          valueFrom:
            configMapKeyRef:
              name: elasticsearch-credentials
              key: ELASTICSEARCH_USERNAME
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: elasticsearch-credentials
              key: ELASTICSEARCH_PASSWORD
        ports:
        - containerPort: 9200
        - containerPort: 9300
        resources:
          requests:
            memory: "1Gi"
          limits:
            memory: "2Gi"

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: elasticsearch
  name: elasticsearch-svc
  namespace: elastic
spec:
  ports:
  - name: elasticsearch-rest
    nodePort: 30920
    port: 9200
    protocol: TCP
    targetPort: 9200
  - name: elasticsearch-nodecom
    nodePort: 30930
    port: 9300
    protocol: TCP
    targetPort: 9300
  selector:
    app: elasticsearch
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-credentials
  namespace: elastic
data:
  ELASTICSEARCH_USERNAME: admin
  ELASTICSEARCH_PASSWORD: admin
