apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: ghcr.io/imkunyoung/efk-poc/efkpoc
      context: ../../../EFK-POC
      jib: {}
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:latest'
deploy:
  kustomize: {}
